# Dependencies
markdown:         kramdown 
highlighter:      rouge 

# Permalinks
permalink:        pretty
relative_permalinks: false 

# Setup
title:            "Dark Matters" 
tagline:          'SECRET MYSTERIES OF THE UNKNOWN UNIVERSE ... AND BEYOND'
description:      'Podcast and Live Show <br /> First Thursday of the Month, 11:59 pm at the <a href="http://www.packtheater.com">Pack Theater</a>'
url:              "http://www.darkmattersshow.com"
baseurl: ""

locale                   : "en"
title_separator          : "-"
teaser                   : "DarkMattersTeaser.png"
author:
  name:           'Michael Bilow'
  url:            "http://jeopardyhotties.tumblr.com/post/117059282149/april-catch-up-part-one"

twitter:
  username               : darkmattersshow
facebook:
  username               : darkmattersshow
social:
  type                   : Organization # Person or Organization (defaults to Person)


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


gems: [jekyll-paginate, jekyll-gist]
