# Dependencies
markdown:         kramdown 
highlighter:      rouge 

# Permalinks
permalink:        pretty
relative_permalinks: false 

# Setup
title:            "Dark Matters" 
tagline:          'SECRET MYSTERIES OF THE UNKNOWN UNIVERSE ... AND BEYOND'
description:      'Podcast & Live Show <br />1st Thursdays, 11:59 pm <br /><a href="http://www.packtheater.com">Pack Theater</a> <br />6470 Santa Monica Blvd'
url:              "http://www.darkmattersshow.com"
baseurl: ""
logo: "/assets/darkmatterslogo.png"
timezone: "America/Los_Angeles"

locale                   : "en"
title_separator          : "-"
teaser                   : "/assets/darkmatterscover.png"
author:
  name:           'Michael Bilow'
  url:            "http://jeopardyhotties.tumblr.com/post/117059282149/april-catch-up-part-one"

twitter:
  username               : darkmattersshow
facebook:
  username               : darkmattersshow
social:
  type                   : Organization # Person or Organization (defaults to Person)


paginate:        2 

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/darkmattersshow/darkmattersshow.github.io


gems: [jekyll-paginate, jekyll-gist]
